
export const Routes = {
    home:'/',
    verifyCustomer:'/customers/:id/verify/:code',
    resetPassword:'/customers/:customerId/reset-password',
    login:'/login',
    register:'/register',
    forgotpassword:'/forgotpassword',
    tutors:'/tutors',
    faqs:'/faqs',
    dashboard:'/dashboard',
    contactUs:'/contact-us',
    annonymousCall:'/calling',
    studentCall:'/calling-route/:receiverId',
    tutorsProfile:'/profile/:id',
    studentRequest:'/request/to/:tutorId',
    aboutInfo:'/dashboard/about',
    contactInfo:'/dashboard/contact',
    expertise:'/dashboard/expertise',
    education:'/dashboard/education',
    studyMediums:'/dashboard/mediums',
    newRequest:'/dashboard/new-requests',
    mySessions:'/dashboard/classes',
    feedback:'/dashboard/feedback',
    classRoom:'/class-room',
}